### ISSUE TITLE
Palm::PDB appears to have travelled in time!

### ISSUE THREAD

**Issue by DrHyde** [madsen/Palm-PDB#1]
Palm::PDB's version number seems to have gone backwards. This broke Palm::Treo680MessagesDB and Palm::TreoPhoneCallDB, both of which declared a dependency on Palm::PDB version 1.29. That existed in 2002 - http://search.cpan.org/~arensb/p5-Palm-1.3.0/ - but these days the CPAN index seems to contain your 1.016 instead.

I caught this because I pointed Travis at all my repos (it's a great tool, BTW, and if you don't already use it then I recommend it) and it failed to install the dependency. I've just downgraded the version I depend on to match what's available, but I wonder if there might be some other Palm-ish modules out there that now fail to install because of this. You might like to consider releasing a version that just bumps the version up to 1.3.

**Comment by madsen** [comment]
It looks like brian d foy broke it in af916ecdb5d74bc029293d9577e8948006f742f0.  Palm::PDB was apparently up to 1.36.  I'll probably just bump it up to 1.400 to avoid reducing the number of digits after the decimal.

**Comment by DrHyde** [comment]
Thanks!

**Comment by madsen** [comment]
Version 1.400 released to CPAN today.
